### ISSUE TITLE
net.java.games.input.DirectAndRawInputEnvironmentPlugin is not supported. Found no controllers.

### ISSUE THREAD

**Issue by UNTAGATUN** [Zhadok/poe-controller#1]
PS C:\Users\...\Desktop\poe-controller-0.0.9> java -D"java.library.path"="./poe-controller-files/lib" -Dverbosity=3 -jar poe-controller-0.0.9.jar
Java Virtual Machine specification version: 1.8
Java Virtual Machine specification vendor: Oracle Corporation
Java Virtual Machine specification name: Java Virtual Machine Specification
Java Virtual Machine implementation version: 25.261-b12
Java Virtual Machine implementation vendor: Oracle Corporation
Java Virtual Machine implementation name: Java HotSpot(TM) Client VM
2020-09-11T13:57:33.490 JInputLib::prepare Preparing JInput natives in directory: poe-controller-files\lib
2020-09-11T13:57:33.525 App::main Setting verbosity to 3
2020-09-11T13:57:33.526 ControllerMapping::<init> Initializing ControllerMapping...
2020-09-11T13:57:33.681 ControllerSettings::init Loading config from file: poe-controller-files\settings.json
2020-09-11T13:57:33.858 ControllerSettings::init Loaded config file.
2020-09-11T13:57:33.859 ControllerSettings::init Configuration for controller 'Default controller name':
ConfigCharacterMovement [mouseOffsetCharacterToScreenCenterX=0, mouseOffsetCharacterToScreenCenterY=-20, mouseDistance_ScreenSizeMultiplier=0.4, stickThreshold=1.0E-4]
ConfigMouseMovement [mouseMoveSensitivity=20.0, stickThreshold=0.0, pollRightStickIntervalMS=10]
2020-09-11T13:57:33.860 ActionHandlerKey::<init> Initializing ActionHandlerKey...
2020-09-11T13:57:33.860 ActionHandlerMouse::<init> Initializing ActionHandlerMouse...
2020-09-11T13:57:33.861 ActionHandlerMacro::<init> Initializing ActionHandlerMacro...
2020-09-11T13:57:34.073 App::startPolling Started polling for controller changes
java.lang.UnsatisfiedLinkError: no jinput-dx8 in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at net.java.games.input.DirectInputEnvironmentPlugin.lambda$loadLibrary$0(DirectInputEnvironmentPlugin.java:73)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.java.games.input.DirectInputEnvironmentPlugin.loadLibrary(DirectInputEnvironmentPlugin.java:67)
        at net.java.games.input.DirectInputEnvironmentPlugin.<clinit>(DirectInputEnvironmentPlugin.java:96)
        at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:134)
        at org.zhadok.poe.controller.App.startPolling(App.java:95)
        at org.zhadok.poe.controller.App.main(App.java:245)
java.lang.UnsatisfiedLinkError: no jinput-raw in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at net.java.games.input.RawInputEnvironmentPlugin.lambda$loadLibrary$0(RawInputEnvironmentPlugin.java:73)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.java.games.input.RawInputEnvironmentPlugin.loadLibrary(RawInputEnvironmentPlugin.java:67)
        at net.java.games.input.RawInputEnvironmentPlugin.<clinit>(RawInputEnvironmentPlugin.java:96)
        at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:46)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:134)
        at org.zhadok.poe.controller.App.startPolling(App.java:95)
        at org.zhadok.poe.controller.App.main(App.java:245)
Sep 11, 2020 1:57:34 PM net.java.games.input.ControllerEnvironment log
INFO: net.java.games.input.DirectAndRawInputEnvironmentPlugin is not supported
Found no controllers.
PS C:\Users\...\Desktop\poe-controller-0.0.9>
[poe-controller.log](https://github.com/Zhadok/poe-controller/files/5210943/poe-controller.log)

**Comment by Zhadok** [comment]
Closed with v0.0.15
